#!/bin/sh
pdflatex -interaction nonstopmode bank_effectualness_short.tex
bibtex bank_effectualness_short
pdflatex -interaction batchmode bank_effectualness_short.tex
pdflatex -interaction batchmode bank_effectualness_short.tex

